//////////// VARIAVEIS DA APLICACAO //////
const MODE_MASTER_SERVER = "bruno";
const COMPANY_ID = 10;
const VERSION = '1.2'
const BUILD = 21
// NAO ALTERAR //
const MODE_IFRAME = MODE_MASTER_SERVER;
const MODE_AUTH_SERVER = "local";
const MODE_APP_SERVER = "local";
const PROJECT_NAME = "luterana_system";
const DEFAULT_SERVER_NAME = "application";
const SYSTEM_COMPLETE = false;
const MODE_SERVER = 'app'

export {
  MODE_MASTER_SERVER,
  COMPANY_ID,
  MODE_IFRAME,
  MODE_AUTH_SERVER,
  MODE_APP_SERVER,
  PROJECT_NAME,
  DEFAULT_SERVER_NAME,
  SYSTEM_COMPLETE,
  VERSION,
  BUILD,
  MODE_SERVER
};
